# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'InstantMessage' do
pod 'CocoaAsyncSocket', '~> 7.4.3'
end

target 'InstantMessageTests' do

end

target 'InstantMessageUITests' do

end

